apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: classification-explorer
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - deploy_url
  rules:
    - host: deploy_url
      http:
        paths:
          - path: /
            backend:
              serviceName: classification-explorer
              servicePort: http
